### ISSUE TITLE
Property for logical equivalence

### ISSUE THREAD

**Issue by dr-shorthair** [CSIRO-enviro-informatics/loci-ont#13]
Propose addition of property 
```
loci:equivalent
```
to relate an individual feature from one geography or dataset with a feature from another geography or dataset which is intended to represent the same real-world entity. 

Use of `loci:equivalent` would allow representations using slightly different geometrical bases (e.g. aggregates of DGGS cells, ASGS meshblocks, surveyed geometries) to be linked, in situations where a purely geometrical computation might not get to a `geo:sfEquals` relationships because of differing precision, slivers, etc,. When the data provider's intention is that they match, then this predicate can be used to make that assertion. The provenance of the assertion maybe be recorded in the usual way in a link-set. 

Related to #11 

Interested in views from @jyucsiro @benjaminleighton @ashleysommer @nicholascar

**Comment by dr-shorthair** [comment]
FWIW the canonical use-case is to relate a Feature to its equivalent DGGS aggregate.

**Comment by benjaminleighton** [comment]
That sounds ok to me. Is an alternative to describe the abstract entity that each geometry represents and link the geometries to that entity? That way the geometries are linked through the abstract entity. This is also handy because if there are other relationships from that abstract entity to, for example, governance structures, then it is possible to navigate from the spatial to these governance relationships.

**Comment by dr-shorthair** [comment]
Yes it might be. But we already have ontologies for ASGS, GNAF, Place-Names, etc that have additional properties on their feature-types, as well as conventions about their geometrical representations. So there needs to a feature-feature-equivalence predicate in the system to manage these. I think it is a small but clear gap.

**Comment by jyucsiro** [comment]
@dr-shorthair could you provide an example? i understand the semantics, but would like to see them against some test-cases/examples

**Comment by dr-shorthair** [comment]
- Gazetted-LGA-GlenEira* -equivalent-> ASGS-LGA-GlenEira

*anticipating that we might have actual LGA polygons at some point

- AustraliaPost-postcode-3168** -equivalent-> ASGS-PostalArea-3168 

**anticipating that we might have actual AusPost polygons at some point haha

- Geofab-OvensRiver -equivalent-> AusPIX-OvensRIver

**Comment by dr-shorthair** [comment]
Note that this explicitly *not* the same as `geo:sfEquals`. 
It is a logical/fiat relationship, not a geometrical equivalence. 
How you choose to use this relationship would be application-specific. 
It is complementary to the `isPartOf`/`hasPart` relations we added last month.

**Comment by nicholascar** [comment]
Closed by Commit https://github.com/CSIRO-enviro-informatics/loci-ont/commit/244662ef4cc3c752ce7226daa9b2201a2f4b3a51 standing in for PR #14
